# NumPy Practice
This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the NumPy documentation.

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.



In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([5, 6, 7])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[3, 7, 8],
               [6, 8, 2]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[4, 6, 7],
                [6, 3, 1]],
               [[2, 6, 9],
                [1, 5, 2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.


In [3]:
# Attributes of 1-dimensional array 
# (shape, number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd

number_data = pd.DataFrame(a1.reshape(1, 3),
                           index=["Numbers"],
                          columns=["num1","num2","num3"])
number_data

num1  num2  num3
Numbers     5     6     7

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
range_array1 = np.arange(0, 100, 3)
range_array1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1 = np.random.randint(10, size=(7, 2))
random_array1

array([[1, 2],
       [7, 0],
       [8, 4],
       [6, 6],
       [4, 4],
       [3, 7],
       [8, 3]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random((3, 5))
random_array2

array([[0.5266434 , 0.86333688, 0.30274178, 0.62372868, 0.12345217],
       [0.49160489, 0.26819404, 0.71987864, 0.28925864, 0.2259692 ],
       [0.84060248, 0.40395681, 0.76587183, 0.3650936 , 0.21422059]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3 = np.random.randint(0, 10, size=(4, 6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4 = np.random.randint(1, 9, size=(3, 7))
# print(random_array4)

# Find the unique numbers in the array you just created
np.unique(random_array4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([4, 7, 4, 7, 4, 5, 8])

In [32]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[4, 7, 4, 7, 4, 5, 8],
       [7, 3, 6, 1, 4, 2, 8]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2, :2]

array([[4, 7],
       [7, 3]])

In [34]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
random_array5 = np.random.randint(0, 10, size=(3, 5))
ones2 = np.ones((3, 5))

In [35]:
# Add the two arrays together
random_array5 + ones2

array([[ 6.,  2., 10.,  2., 10.],
       [ 4.,  8.,  7.,  9.,  8.],
       [ 5.,  2.,  5.,  8., 10.]])

In [36]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones((5, 3))

In [37]:
# Try add the array of ones and the other most recent array together
random_array5 + ones3
# Error arises becuse shapes are not compatible

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [38]:
random_array5 + ones3.T

array([[ 6.,  2., 10.,  2., 10.],
       [ 4.,  8.,  7.,  9.,  8.],
       [ 5.,  2.,  5.,  8., 10.]])

In [40]:
# Create another array of ones of shape (3, 5)
ones4 = np.ones((3, 5))

In [42]:
# Subtract the new array of ones from the other most recent array
random_array5 - ones4

array([[4., 0., 8., 0., 8.],
       [2., 6., 5., 7., 6.],
       [3., 0., 3., 6., 8.]])

In [43]:
# Multiply the ones array with the latest array
random_array5 * ones4

array([[5., 1., 9., 1., 9.],
       [3., 7., 6., 8., 7.],
       [4., 1., 4., 7., 9.]])

In [44]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2

array([[25,  1, 81,  1, 81],
       [ 9, 49, 36, 64, 49],
       [16,  1, 16, 49, 81]], dtype=int32)

In [45]:
# Do the same thing with np.square()
np.square(random_array5)

array([[25,  1, 81,  1, 81],
       [ 9, 49, 36, 64, 49],
       [16,  1, 16, 49, 81]], dtype=int32)

In [46]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

5.4

In [47]:
# Find the maximum of the latest array using np.max()
np.max(random_array5)

9

In [48]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

1

In [49]:
# Find the standard deviation of the latest array
np.std(random_array5)

2.8472208672083497

In [50]:
# Find the variance of the latest array
np.var(random_array5)

8.106666666666667

In [51]:
# Reshape the latest array to (3, 5, 1)
random_array5.reshape(3, 5, 1)

array([[[5],
        [1],
        [9],
        [1],
        [9]],

       [[3],
        [7],
        [6],
        [8],
        [7]],

       [[4],
        [1],
        [4],
        [7],
        [9]]])

In [54]:
# Transpose the latest array
random_array5.T

array([[5, 3, 4],
       [1, 7, 1],
       [9, 6, 4],
       [1, 8, 7],
       [9, 7, 9]])

In [55]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
random_array6 = np.random.randint(0, 10, size=(3, 3))
random_array7 = np.random.randint(0, 10, size=(3, 2))

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array6, random_array7)

array([[56, 72],
       [72, 74],
       [63, 28]])

In [57]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
random_array8 = np.random.randint(0, 10, size=(4, 3))
random_array9 = np.random.randint(0, 10, size=(4, 3))

In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array8, random_array9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [61]:
# Take the latest two arrays, perform a transpose on one of them and then perform  a dot product on them both
np.dot(random_array8.T, random_array9)

array([[ 28,  44,  42],
       [ 58,  91,  77],
       [108, 131,  90]])

In [62]:
np.dot(random_array8, random_array9.T)

array([[ 64,  73,  18,   8],
       [131, 115,  28,  42],
       [120, 103,  26,  40],
       [ 30,  32,  14,   4]])

In [69]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
random_array10 = np.random.randint(0, 10, size=(3, 3))
random_array11 = np.random.randint(0, 10, size=(3, 3))

In [70]:
# Compare the two arrays with '>'
random_array10 > random_array11

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [71]:
# Compare the two arrays with '>='
random_array10 >= random_array11

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [72]:
# Find which elements of the first array are greater than 7
random_array10 > 7

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [73]:
# Which parts of each array are equal? (try using '==')
random_array10 == random_array11

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [78]:
random_array10

array([[8, 6, 0],
       [0, 8, 8],
       [3, 8, 2]])

In [74]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array10)

array([[0, 6, 8],
       [0, 8, 8],
       [2, 3, 8]])

In [75]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array10)

array([[2, 1, 0],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [76]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array10)

0

In [79]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array10)

2

In [80]:
np.argmin(random_array10, axis=1)

array([2, 0, 2], dtype=int64)

In [81]:
# Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created
np.argmax(random_array10, axis=1)

array([0, 1, 1], dtype=int64)

In [82]:
# Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created
np.argmin(random_array10, axis=0)

array([1, 0, 0], dtype=int64)

In [83]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.16128571,  0.40405086,  1.8861859 ,  0.17457781,  0.25755039],
       [-0.07444592, -1.91877122, -0.02651388,  0.06023021,  2.46324211],
       [-0.19236096,  0.30154734, -0.03471177, -1.16867804,  1.14282281]])

In [84]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])